USE [master]
GO
/****** Object:  Database [Storage]    Script Date: 19.11.2019 13:19:56 ******/
CREATE DATABASE [Storage]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Storage', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Storage.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Storage_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Storage_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Storage] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Storage].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Storage] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Storage] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Storage] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Storage] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Storage] SET ARITHABORT OFF 
GO
ALTER DATABASE [Storage] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Storage] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Storage] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Storage] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Storage] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Storage] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Storage] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Storage] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Storage] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Storage] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Storage] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Storage] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Storage] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Storage] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Storage] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Storage] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Storage] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Storage] SET RECOVERY FULL 
GO
ALTER DATABASE [Storage] SET  MULTI_USER 
GO
ALTER DATABASE [Storage] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Storage] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Storage] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Storage] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Storage] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Storage', N'ON'
GO
ALTER DATABASE [Storage] SET QUERY_STORE = OFF
GO
USE [Storage]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Storage]
GO
/****** Object:  Table [dbo].[Files]    Script Date: 19.11.2019 13:19:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Files](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IdFile] [nvarchar](max) NULL,
	[FileData] [varbinary](max) NULL,
	[CreationAuthor] [nvarchar](max) NULL,
	[CreationDate] [datetime] NULL,
	[Title] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 19.11.2019 13:19:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](max) NULL,
	[Password] [nvarchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Storage] SET  READ_WRITE 
GO
